### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ddavidebor** [indiependente/autoEqMac#2]
Getting this error during install:

```
# github.com/c-bata/go-prompt/internal/term
../go/src/github.com/c-bata/go-prompt/internal/term/term.go:22:7: assignment mismatch: 1 variable but termios.Tcgetattr returns 2 values
../go/src/github.com/c-bata/go-prompt/internal/term/term.go:22:26: too many arguments in call to termios.Tcgetattr
	have (uintptr, *unix.Termios)
	want (uintptr)
```

**Comment by indiependente** [comment]
Hi @ddavidebor,

The error you're reporting seems to be experienced by other users as well and I can reproduce it too.
The problem lies in the go-prompt module and here is an issue raised two days ago that highlights it: https://github.com/c-bata/go-prompt/issues/215

Hopefully this will get sorted by the go-prompt developers soon.

If you don't mind, you can alternatively install `autoEqMac` via release https://github.com/indiependente/autoEqMac/releases/tag/v0.1.0

Please let me know if that is not convenient to you and I'll try my best to help 😀

**Comment by indiependente** [comment]
Hi @ddavidebor ,

Could you please upgrade autoEqMac to the new version and retry?

You should be able to do that by simply running 
```bash
go install github.com/indiependente/autoEqMac@v0.1.3
```
Or downloading from the release page: https://github.com/indiependente/autoEqMac/releases/tag/v0.1.3

Let me know how it goes 😃

**Comment by ddavidebor** [comment]
Fixed, thanks

**Comment by ddavidebor** [comment]
Fixed, thanks.
